### ISSUE TITLE
QRCode failing

### ISSUE THREAD

**Issue by portalzine** [wolfgangasdf/WebRemoteControl#3]
QRCode fails to generate, when using the compiled version on Mac "bin/webremotecontrol".
Works fine, when using `./gradlew run`

Cheers
Alex

Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.google.zxing.qrcode.encoder.Encoder.chooseMode(Encoder.java:247)
	at com.google.zxing.qrcode.encoder.Encoder.encode(Encoder.java:111)
	at com.google.zxing.qrcode.QRCodeWriter.encode(QRCodeWriter.java:78)
	at net.glxn.qrgen.core.AbstractQRCode.createMatrix(AbstractQRCode.java:86)
	at net.glxn.qrgen.javase.QRCode.writeToStream(QRCode.java:150)
	at net.glxn.qrgen.core.AbstractQRCode.stream(AbstractQRCode.java:62)
	at WebRemoteControl.showQRCode(WebRemoteControl.kt:27)
	at WebRemoteControl$showGUI$1._init_$lambda$0(WebRemoteControl.kt:96)
	at java.desktop/java.awt.Button.processActionEvent(Unknown Source)
	at java.desktop/java.awt.Button.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.nio.charset.UnsupportedCharsetException: SJIS
	at java.base/java.nio.charset.Charset.forName(Unknown Source)
	at com.google.zxing.common.StringUtils.<clinit>(StringUtils.java:35)

**Comment by wolfgangasdf** [comment]
Does it work now with the new library?

**Comment by portalzine** [comment]
Yes working perfectly now!

**Comment by wolfgangasdf** [comment]
.
